# Generated by Django 5.1.6 on 2025-02-26 03:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('em_preparo', 'Em Preparo'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('taxa_entrega', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tipo_entrega', models.CharField(choices=[('retirada', 'Retirada no Local'), ('delivery', 'Delivery'), ('comer no local', 'Comer no local')], default='retirada', max_length=20)),
                ('endereco_entrega', models.TextField(blank=True, null=True)),
                ('cep_entrega', models.CharField(blank=True, max_length=9, null=True)),
                ('previsao_entrega', models.DateTimeField(blank=True, null=True)),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito')], max_length=20)),
                ('pagamento_confirmado', models.BooleanField(default=False)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('codigo_transacao', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'ordering': ['-data_pedido'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('desconto_item', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('observacoes_item', models.TextField(blank=True, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['-data_pedido'], name='pedidos_ped_data_pe_4b872a_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['status'], name='pedidos_ped_status_65e537_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['cliente'], name='pedidos_ped_cliente_06d92d_idx'),
        ),
        migrations.AddIndex(
            model_name='itempedido',
            index=models.Index(fields=['pedido', 'produto'], name='pedidos_ite_pedido__5d4d74_idx'),
        ),
    ]
